### ISSUE TITLE
Reciever node not starting - not picking up the /etc/ssh volume

### ISSUE THREAD

**Issue by belljaf88** [ShiromMakkad/docker-pihole-sync#3]
I am having difficulties getting the reciever container to work.
Using the example config I can create the container however it immediately exits giving the error:

Please define an /etc/ssh config path. This should be a physical path, such as: -v "~/piholesync/etc-ssh:/etc/ssh"

here is the relevant part of my compose file:
``` 
pihole-sync-receiver:
    image: shirom/pihole-sync:latest
    container_name: pihole-sync-receiver
    volumes:
        - /share/container/piholesync/root:/root
        - /share/container/piholesync/etc-ssh:/etc/ssh
        - /share/container/pihole/etc-pihole:/mnt/etc-pihole
        - /share/container/pihole/etc-dnsmasq.d:/mnt/etc-dnsmasq.d
    environment:
        - "NODE=receiver"
    ports:
        - '2223:22'
 ```

If I execute docker inspect pihole-sync-receiver then this is in the output under mounts:
```
"Type": "bind",
                "Source": "/share/container/piholesync/etc-ssh",
                "Destination": "/etc/ssh",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
```
I assume this relates to this in the entryPoint.sh:
```
if [[ "${NODE,,}" == "receiver" ]]; then
    if ! mount | grep -q "/etc/ssh"; then
        echo "Please define an /etc/ssh config path."
        echo "This should be a physical path, such as:"
        echo "-v \"~/piholesync/etc-ssh:/etc/ssh\""
        exit 6
```
But unsure how to resolve it.
