### ISSUE TITLE
Invalid port specification 133342

### ISSUE THREAD

**Issue by AndyYangUK** [ShiromMakkad/docker-pihole-sync#4]
Hi there
Trying to install this via docker-compose on my Synology NAS, however I'm getting an error relating to port 133342? Not sure where this port is used so could you provide some insight?

**SSH Output:**
```
sudo docker-compose up -d
Creating network "pihole_pihole_network" with driver "macvlan"
Creating network "pihole_default" with the default driver
Creating pihole-sync-receiver ... error
Creating pihole               ...

Creating pihole               ... done

ERROR: for pihole-sync-receiver  Cannot create container for service pihole-sync-receiver: b'invalid port specification: "133342"'
ERROR: Encountered errors while bringing up the project.
```

Docker-compose file
```
version: '2' # version 2 is necessary. v3 does not support ipam

# Reference: https://www.reddit.com/r/synology/comments/gmfta3/pihole_5_on_synology_using_docker_simplified_with/

services:
 pihole:
   container_name: pihole
   image: pihole/pihole:latest
   networks:
     pihole_network:
       ipv4_address: 192.168.0.200
   #cap_add:
   #  - NET_ADMIN # add if using DHCP in pihole
   volumes:
     - "./pihole/:/etc/pihole/"
     - "./dnsmasq.d/:/etc/dnsmasq.d/"
   dns:
     - 127.0.0.1
     - 8.8.8.8
   ports:
     - 443/tcp
     - 53/tcp
     - 53/udp
     - 67/udp
     - 80/tcp
   environment:
     TZ: Europe/London
     ServerIP: 192.168.0.200
     WEBPASSWORD: ^y6yL5LY*4go^o
   restart: unless-stopped
   
 # See https://github.com/ShiromMakkad/docker-pihole-sync  
 pihole-sync-receiver:
   image: shirom/pihole-sync:latest
   container_name: pihole-sync-receiver
   volumes:
     - "./piholesync/root/:/root/"
     - "./piholesync/etc-ssh/:/etc/ssh/"
     - "./pihole/:/etc/pihole/"
     - "./dnsmasq.d/:/etc/dnsmasq.d/"
   environment:
     - "NODE=receiver"
   ports:
     - 2222:22

networks:
 pihole_network:
   driver: macvlan
   driver_opts:
     parent: ovs_eth0
   ipam:
     config:
       - subnet: 192.168.0.0/24
         gateway: 192.168.0.1
         ip_range: 192.168.0.200/32

```
