### ISSUE TITLE
Pihole-sync-receiver Error 139

### ISSUE THREAD

**Issue by RichardHyde** [ShiromMakkad/docker-pihole-sync#9]
I'm having problems setting up docker-pinhole-sync between two Raspberry PIs. The pihole-sync-receiver docker container exits with error 139 upon start-up. Nothing in the log file as far as I can find. It's running on a PI Zero (non-W) if that's any help.

Here is the docker-compose.yml I'm using :-

```
version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
#    ports:
#      - "53:53/tcp"
#      - "53:53/udp"
#      - "67:67/udp"
#      - "8080:80/tcp"
    network_mode: host
    environment:
      TZ: 'Europe/London'
      WEBPASSWORD: "PASSWORD"
      ServerIP: 10.0.0.4
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  pihole-sync-receiver:
    image: shirom/pihole-sync:latest
    container_name: pihole-sync-receiver
    volumes:
        - ./piholesync/root:/root
        - ./piholesync/etc-ssh:/etc/ssh
        - ./etc-pihole:/mnt/etc-pihole
        - ./etc-dnsmasq.d:/mnt/etc-dnsmasq.d
    environment:
        NODE: "receiver"
    ports:
        - "22222:22"
```

Let me know if anyone needs anymore information. Thanks in advance.
